spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/managingrestauranttickets
#server.port=7080
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

#Spring security config
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.example.com
#jwt.secret=your-256-bit-secret-key
#jwt.expiration=36000000

#REQUIRE FOR CORS
# Configuration du serveur Spring Boot
server.port=8080
# Écoute sur toutes les interfaces réseau
server.address=0.0.0.0

# Pour le développement, vous pouvez aussi utiliser:
# Activer les logs détaillés
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG

# Désactiver la sécurité CSRF (pour le développement seulement)
#spring.security.enabled=false
