spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/managingrestauranttickets
server.port=8080
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
server.address=0.0.0.0
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG

#Spring security config
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.example.com
#jwt.secret=your-256-bit-secret-key
#jwt.expiration=36000000

# Désactiver la sécurité CSRF (pour le développement seulement)
#spring.security.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# PayDunya Configuration
paydunya.master-key=QrEhNIfs-Yk6s-QIHb-S0PE-9Jel13qnYkjY
paydunya.private-key=test_private_6PM1bjx5qL56M8PkW8NzIyA7fTk
paydunya.public-key=test_public_ytzg3SbCj60gBJsz5jCE9yQ1xIT
paydunya.token=yao4jLTxlYHUUGlnp3wa
paydunya.mode=test  # "test" ou "live"

# URLs de callback
paydunya.return-url=http://localhost:8080/api/payments/return
paydunya.cancel-url=http://localhost:8080/api/payments/cancel
paydunya.webhook-url=http://localhost:8080/api/payments/webhook

#paydunya:
#base-url-test: https://app.paydunya.com/sandbox-api/v1
#base-url-live: https://app.paydunya.com/api/v1
#store-name: "Mon Application"
#callback-url: https://votre-domaine.com/api/payment/ipn